BarcodeSystem/urls.py
import xadmin
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('admin/', admin.site.urls),
    # 使用xadmin后台，不使用系统自带的admin
    path('admin/', xadmin.site.urls),
    path('product/', include('bc_product.urls', namespace='product')),
    path('production/', include('bc_production.urls', namespace='production')),
    path('rmaterial/', include('bc_rmaterial.urls', namespace='rmaterial')),
    path('formula/', include('bc_formula.urls', namespace='formula')),
]

bc_formula/urls.py
from django.urls import path
from . import views

app_name = 'formula'
urlpatterns = [
    # 引向配方保存视图
    path('save_formula', views.save_formula, name='save_formula'),
    # 引向配方查询视图
    path('query_formula<int:num>', views.query_formula, name='query_formula'),
    path('update_formula', views.update_formula, name='update_formula'),
]

bc_test/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path()
]

bc_formula/models.py
from django.db import models


class Pb(models.Model):
    pbbh = models.CharField(primary_key=True, max_length=50, verbose_name='配方编号')
    pbname = models.CharField(max_length=50, verbose_name='配方名称')
    pftype = models.CharField(verbose_name='配方类型', max_length=15)  # 0:标准配方， 1:比例配方
    scsx = models.IntegerField(blank=True, null=True, verbose_name='生产顺序')
    scxh = models.IntegerField(blank=True, null=True, verbose_name='默认生产线')  # 1
    yx = models.BooleanField(default=True, verbose_name='有效配方')
    bz = models.CharField(max_length=300, blank=True, null=True, verbose_name='备注')
    validity = models.BooleanField(default=False, verbose_name='有无产品')  # 产品与配方一对一关系，如配方有了对应的产品，则改为True

    def __str__(self):
        return str(self.pbbh)

    class Meta:
        db_table = 'pb'
        verbose_name = '配方'
        verbose_name_plural = '配方信息'


class Pbf(models.Model):
    pbbh = models.ForeignKey('Pb', on_delete=models.CASCADE, verbose_name='配方编号')  # 关联配方主表
    plno = models.IntegerField(verbose_name='序号')
    ylid = models.ForeignKey('bc_rmaterial.Ylinfo', on_delete=models.CASCADE, verbose_name='原料代码')  # 关联的原料删除不影响此数据
    ylname = models.CharField(max_length=50, verbose_name='原料名称')
    bzgl = models.FloatField(verbose_name='标准值')
    topz = models.FloatField(verbose_name='上限', blank=True, null=True)
    lowz = models.FloatField(verbose_name='下限', blank=True, null=True)
    dw = models.CharField(verbose_name='单位', max_length=20)  # 默认kg
    jno = models.IntegerField(verbose_name='投料顺序')  # 默认原料分类ID;
    lt = models.BooleanField(default=True, verbose_name='称零头')
    zs = models.BooleanField(default=True, verbose_name='追溯')

    def __str__(self):
        return str(self.pbbh)

    class Meta:
        db_table = 'pbf'
        verbose_name = '配方明细'
        verbose_name_plural = '配方明细'

bc_formula/views.py
from django.shortcuts import render, redirect
from django.db import connection
from django.http import JsonResponse
from bc_rmaterial.models import *
from django.core import serializers
from .models import *
import re


def update_formula(request):
    '''
        修改配方时，由此视图处理
    '''
    pb_bh = request.GET.get('pb_bh')
    # 将查询的数据返回到前端页面
    pb = Pb.objects.get(pbbh=pb_bh)
    pbbh = pb.pbbh
    pbname = pb.pbname
    pftype = pb.pftype
    scsx = pb.scsx
    scxh = pb.scxh
    yx = pb.yx
    bz = pb.bz
    pbf_list = serializers.serialize('json', pb.pbf_set.all().order_by('pk'))
    return JsonResponse({'pbbh': pbbh, 'pbname': pbname, 'pftype': pftype, 'scsx': scsx, 'scxh': scxh, 'yx': yx,
                         'bz': bz, 'pbf_list': pbf_list})


def save_formula(request):
    '''
        保存配方时，由此视图处理
    '''
    proof = request.POST.get('proof')
    pbbh = request.POST.get('pbbh')
    pbname = request.POST.get('pbname')
    pftype = request.POST.get('pftype')
    scsx = request.POST.get('scsx')
    scxh = request.POST.get('scxh')
    yx = request.POST.get('yx', 0)
    bz = request.POST.get('bz')
    addanother = request.POST.get('_addanother')
    add_edit = request.POST.get('_continue')
    plno = request.POST.getlist('plno')
    ylid = request.POST.getlist('datas')
    ylname = request.POST.getlist('data_name')
    bzgl = request.POST.getlist('bzgl')
    topz = request.POST.getlist('topz')
    lowz = request.POST.getlist('lowz')
    dw = request.POST.getlist('dw')
    jno = request.POST.getlist('jno')
    hlt = request.POST.getlist('hlt')
    hzs = request.POST.getlist('hzs')
    yx = True if yx == '1' else False
    pattern = re.compile(r'\.+')
    # 判断以下字段，有一项为t,重定向至起始页面
    if (pbbh == '' or pbname == '' or scsx == '' or scxh == '' or pattern.search(scsx) or pattern.search(scxh) or
            plno.count('') or ylid.count('') or ylname.count('') or bzgl.count('') or topz.count('') or lowz.count('') or jno.count('')):
        return redirect('/admin/bc_production/scjhb/add/')
    new_plno = []
    new_bzgl = []
    new_topz = []
    new_lowz = []
    new_jno = []
    new_hlt = []
    new_hzs = []
    # 将这些字段值转换为Int或float类型进行存储，不然会报类型错误
    for plno_single in plno:
        new_plno.append(int(plno_single))
    for bzgl_single in bzgl:
        new_bzgl.append(float(bzgl_single))
    for topz_single in topz:
        new_topz.append(float(topz_single))
    for lowz_single in lowz:
        new_lowz.append(float(lowz_single))
    for jno_single in jno:
        new_jno.append(int(jno_single))
    for hlt_single in hlt:
        if hlt_single == '1':
            new_hlt.append(True)
        else:
            new_hlt.append(False)
    for hzs_single in hzs:
        if hzs_single == '1':
            new_hzs.append(True)
        else:
            new_hzs.append(False)
    cursor = connection.cursor()
    # 判断proof字段，无值说明是新增
    if not proof:
        # 执行新增配方过程，若成功返回指定页面，反之返回列表页
        try:
            cursor.callproc('pb_I', (pbbh, pbname, pftype, scsx, scxh, yx, bz, new_plno, ylname, new_bzgl, new_topz,
                                     new_lowz, dw, new_jno, new_hlt, new_hzs, ylid))
            connection.commit()
            cursor.close()
            connection.close()
            if addanother is None and add_edit is None:
                return redirect('/admin/bc_formula/pb/')
            elif addanother is not None and add_edit is None:
                return redirect('/admin/bc_formula/pb/add/')
            elif addanother is None and add_edit is not None:
                return redirect('/admin/bc_formula/pb/' + pbbh + '/update/')
        except Exception as e:
            print(e)
            cursor.close()
            connection.close()
            return redirect('/admin/bc_formula/pb/')  # 后续会返回一个错误页面
    # 否则修改
    else:
        # 执行新增配方过程，若成功返回指定页面，反之返回列表页
        try:
            cursor.callproc('pb_U', (pbbh, pbname, pftype, scsx, scxh, yx, bz, new_plno, ylname, new_bzgl, new_topz,
                                     new_lowz, dw, new_jno, new_hlt, new_hzs, ylid, proof))
            connection.commit()
            cursor.close()
            connection.close()
            if addanother is None and add_edit is None:
                return redirect('/admin/bc_formula/pb/')
            elif addanother is not None and add_edit is None:
                return redirect('/admin/bc_formula/pb/add/')
            elif addanother is None and add_edit is not None:
                return redirect('/admin/bc_formula/pb/' + pbbh + '/update/')
        except Exception as e:
            print(e)
            cursor.close()
            connection.close()
            return redirect('/admin/bc_formula/pb/')  # 后续会返回一个错误页面


def query_formula(request, num):
    # 根据参数值不同，查询的数据也不同，都是普通的查询，具体请看bc_formula.js文件
    if num == 1:
        ylinfo = serializers.serialize('json', Ylinfo.objects.all())
        return JsonResponse({'ylinfo': ylinfo})
    elif num == 2:
        original = request.GET.get('Original')
        pbbh = request.GET.get('pbbh')
        bool = 1
        if pbbh == original:
            return JsonResponse({'bool': bool})
        pb_list = Pb.objects.filter(pbbh=pbbh)
        if pb_list:
            bool = 0
        return JsonResponse({'bool': bool})
    elif num == 3:
        plno = request.GET.get('plno')
        arr = request.GET.getlist('arr')
        plno_bool = 1
        if arr.count(plno):
            return JsonResponse({'plno_bool': plno_bool})
        pbf_list = Pbf.objects.filter(plno=plno)
        if pbf_list:
            plno_bool = 0
        return JsonResponse({'plno_bool': plno_bool})
    elif num == 4:
        current_value = request.GET.get('current_value')
        ylid = Ylinfo.objects.filter(ylid=current_value)
        ylid_bool = 0
        ylname = ''
        zf = ''
        if ylid:
            ylid_bool = 1
            ylname = ylid[0].ylname
            zf = ylid[0].zf_id
        return JsonResponse({'ylid_bool': ylid_bool, 'ylname': ylname, 'zf': zf})
    elif num == 5:
        current_value = request.GET.get('current_value')
        ylname = Ylinfo.objects.filter(ylname=current_value)
        ylname_bool = 0
        ylid = ''
        zf = ''
        if ylname:
            ylname_bool = 1
            ylid = ylname[0].ylid
            zf = ylname[0].zf_id
        return JsonResponse({'ylname_bool': ylname_bool, 'ylid': ylid, 'zf': zf})

templates/bc_formula/formula_add.html
{% extends base_template %}
{% load i18n %}

{% load xadmin_tags %}
{% load crispy_forms_tags %}
{% block extrastyle %}
    <link rel="stylesheet" href="/static/bootstrap-3.3.7-dist/css/bootstrap.css">
    <script src="/static/js/jquery-1.12.4.min.js"></script>
    <script src="/static/bootstrap-3.3.7-dist/js/bootstrap.min.js"></script>
    <script src="/static/js/template-web.js"></script>
    <script src="/static/js/barcodesystem/bc_formula/bc_formula_add.js"></script>
    <link rel="stylesheet" href="/static/css/formula.css">
{% endblock %}

{% block bodyclass %}{{ opts.app_label }}-{{ opts.object_name.lower }} change-form{% endblock %}

{% block nav_title %}{% if model_icon %}<i class="{{model_icon}}"><sub class="fa fa-{% if add%}plus{%else%}pencil{%endif%}"></sub></i> {% endif %}
{{ title }}{% endblock %}

{% block content %}
<div class="container">
    <form class="form-horizontal" method="post" action="{% url 'formula:save_formula' %}" id="form_submit">
        {%csrf_token%}
        <div class="form-group has-feedback">
            <label class="col-sm-2 control-label">配方编号<span class="" style="color: red">*</span></label>
            <div class="col-sm-4 form-box">
                <input type="text" class="form-control" name="pbbh" id="pbbh" value="" autocomplete="off">
                <span class="tips"></span>
            </div>
            <label class="col-sm-2 control-label">配方名称<span class="" style="color: red">*</span></label>
            <div class="col-sm-4 form-box">
                <input type="text" class="form-control" name="pbname" id="pbname" value="">
                <span class="tips"></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">配方类型</label>
            <div class="col-sm-4 form-box">
                <select class="form-control" name="pftype" id="pftype">
                    <option value="0">标准配方</option>
                    <option value="1">比例配方</option>
                </select>
            </div>
            <label class="col-sm-2 control-label">生产顺序<span class="" style="color: red">*</span></label>
            <div class="col-sm-4 form-box">
                <input type="number" class="form-control" name="scsx" id="scsx" value="">
                <span class="tips"></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">生产线<span class="" style="color: red">*</span></label>
            <div class="col-sm-4 form-box">
                <input type="number" class="form-control" name="scxh" id="scxh" value="1">
                <span class="tips"></span>
            </div>
            <label class="col-sm-2 control-label">备注</label>
            <div class="col-sm-4 form-box">
                <input type="text" class="form-control" name="bz" id="bz">
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-1 col-sm-4">
                <label class="control-label">
                    <input type="checkbox" name="yx" checked="checked" value="1" id="yx"> 有效配方
                </label>
            </div>
        </div>
        <div class="navbar navbar-default">
            <div class="navbar-header">
                <span class="navbar-brand">增加配方明细</span>
            </div>
            <a href="javascript:;" class="add-detailed glyphicon glyphicon-plus navbar-right"></a>
        </div>
        <table class="table table-condensed">
            <thead class="thead">
                <tr class="tr">
                    <th class="b_title">序号<span class=""></span></th>
                    <th class="b_title">原料代码<span class="" style="color: red">*</span></th>
                    <th class="b_title">原料名称<span class="" style="color: red">*</span></th>
                    <th class="b_title">标准值<span class="" style="color: red">*</span></th>
                    <th class="b_title">上限</th>
                    <th class="b_title">下限</th>
                    <th class="b_title">单位</th>
                    <th class="b_title">投料顺序<span class="" style="color: red">*</span></th>
                    <th class="b_title">称零头</th>
                    <th class="b_title">追溯</th>
                </tr>
            </thead>
            <tbody class="tbody">
                <tr class="bodytr">
                    <td><input type="text" name="plno" class="plno" value="1" readonly><span class="tips"></span></td>
                    <td>
                        <input list="data" class="form-control datas" name="datas" autocomplete="off" value="">
                        <span class="tips"></span>
                        <datalist id="data">
                            <select class="form-control" name="ylid" id="ylid">
                            </select>
                        </datalist>
                    </td>
                    <td>
                        <input list="data_name" class="form-control data_name" name="data_name" autocomplete="off" value="">
                        <span class="tips"></span>
                        <datalist id="data_name">
                            <select class="form-control" name="ylname" id="ylname">
                            </select>
                        </datalist>
                    </td>
                    <td><input type="text" name="bzgl" class="bzgl" value=""><span class="tips"></span></td>
                    <td><input type="text" name="topz" class="topz" value=""><span class="tips"></span></td>
                    <td><input type="text" name="lowz" class="lowz" value=""><span class="tips"></span></td>
                    <td>
                        <select class="form-control dw" name="dw">
                            <option value="kg">kg</option>
                            <option value="g">g</option>
                        </select>
                    </td>
                    <td><input type="number" name="jno" class="jno" value="" readonly><span class="tips"></span></td>
                    <td>
                        <input type="checkbox" name="lt" checked="checked" value="1" class="lt">
                        <input type="hidden" name="hlt" value="1" class="hlt">
                    </td>
                    <td>
                        <input type="checkbox" name="zs" checked="checked" value="1" class="zs">
                        <input type="hidden" name="hzs" value="1" class="hzs">
                    </td>
                    <td><a href="javascript:;" class="glyphicon glyphicon-remove f_delete"></a></td>
                </tr>
            </tbody>
        </table>
        <div class="form-actions well-sm clearfix">
            <div class="btn-group clearfix show-xs save-group col-xs-12">
                <button type="submit" class="default btn btn-primary col-xs-10" name="_save" data-loading-text="保存中.."><i class="fa fa-save"></i> 保存</button>
                <button type="button" class="more btn btn-primary col-xs-2" data-toggle="collapse" data-target=".nav-collapse.more-btns"><i class="fa fa-ellipsis-vertical"></i></button>
            </div>
            <button type="submit" class="default btn btn-primary hide-xs" name="_save"><i class="fa fa-save"></i> 保存</button>
            <div class="nav-collapse collapse more-btns">
                <input type="submit" class="btn btn-default" value="保存并增加另一个" name="_addanother"  />
                <input type="submit" class="btn btn-default" value="保存并继续编辑" name="_continue" />
            </div>
        </div>
    </form>
</div>
{% endblock %}

templates/bc_formula/formula_update.html
{% extends base_template %}
{% load i18n %}

{% load xadmin_tags %}
{% load crispy_forms_tags %}
{% block extrastyle %}
    <link rel="stylesheet" href="/static/bootstrap-3.3.7-dist/css/bootstrap.min.css">
    <script src="/static/js/jquery-1.12.4.min.js"></script>
    <script src="/static/bootstrap-3.3.7-dist/js/bootstrap.min.js"></script>
    <script src="/static/js/template-web.js"></script>
    <script src="/static/js/barcodesystem/bc_formula/bc_formula_update.js"></script>
    <link rel="stylesheet" href="/static/css/formula.css">
{% endblock %}

{% block bodyclass %}{{ opts.app_label }}-{{ opts.object_name.lower }} change-form{% endblock %}

{% block nav_title %}{% if model_icon %}<i class="{{model_icon}}"><sub class="fa fa-{% if add%}plus{%else%}pencil{%endif%}"></sub></i> {% endif %}
{{ title }}{% endblock %}

{% block content %}
<div class="container">
    <input type="hidden" name="pb_bh" id="pb_bh" value="{{ object_id }}">
    <form class="form-horizontal" method="post" action="{% url 'formula:save_formula' %}" id="form_submit">
    </form>
    <script id="pb" type="text/template">
        {%csrf_token%}
        <div class="form-group has-feedback">
            <label class="col-sm-2 control-label">配方编号<span class="" style="color: red">*</span></label>
            <div class="col-sm-4 form-box">
                <input type="text" class="form-control" name="pbbh" id="pbbh" value="<%- pbbh %>" autocomplete="off">
                <span class="tips"></span>
            </div>
            <label class="col-sm-2 control-label">配方名称<span class="" style="color: red">*</span></label>
            <div class="col-sm-4 form-box">
                <input type="text" class="form-control" name="pbname" id="pbname" value="<%- pbname %>">
                <span class="tips"></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">配方类型</label>
            <div class="col-sm-4 form-box">
                <select class="form-control" name="pftype" id="pftype">
                    <% if (pftype == '0')
                        { %> <option value="0">标准配方</option>
                             <option value="1">比例配方</option> <% }
                    else
                        { %> <option value="1">比例配方</option>
                             <option value="0">标准配方</option> <% }
                    %>
                </select>
            </div>
            <label class="col-sm-2 control-label">生产顺序<span class="" style="color: red">*</span></label>
            <div class="col-sm-4 form-box">
                <input type="number" class="form-control" name="scsx" id="scsx" value="<%- scsx %>">
                <span class="tips"></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">生产线<span class="" style="color: red">*</span></label>
            <div class="col-sm-4 form-box">
                <input type="number" class="form-control" name="scxh" id="scxh" value="<%- scxh %>">
                <span class="tips"></span>
            </div>
            <label class="col-sm-2 control-label">备注</label>
            <div class="col-sm-4 form-box">
                <input type="text" class="form-control" name="bz" id="bz" value="<%- bz %>">
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-1 col-sm-4">
                <label class="control-label">
                    <% if (yx)
                            { %> <input type="checkbox" name="yx" checked="checked" id="yx" value="1">有效配方 <% }
                        else
                            { %> <input type="checkbox" name="yx" id="yx" value="1">有效配方 <% }
                    %>
                </label>
            </div>
        </div>
        <div class="navbar navbar-default">
            <div class="navbar-header">
                <span class="navbar-brand">增加配方明细</span>
            </div>
            <a href="javascript:;" class="add-detailed glyphicon glyphicon-plus navbar-right"></a>
        </div>
        <table class="table table-condensed">
            <thead>
                <tr class="tr">
                    <th class="b_title">序号<span class=""></span></th>
                    <th class="b_title">原料代码<span class="" style="color: red">*</span></th>
                    <th class="b_title">原料名称<span class="" style="color: red">*</span></th>
                    <th class="b_title">标准值<span class="" style="color: red">*</span></th>
                    <th class="b_title">上限</th>
                    <th class="b_title">下限</th>
                    <th class="b_title">单位</th>
                    <th class="b_title">投料顺序<span class="" style="color: red">*</span></th>
                    <th class="b_title">称零头</th>
                    <th class="b_title">追溯</th>
                </tr>
            </thead>
            <tbody class="tbody">
                <% for(var i = 0; i < pbf_list.length; i++){ %>
                <tr class="bodytr">
                    <td><input type="text" name="plno" class="plno" value="<%= pbf_list[i].fields.plno %>" readonly><span class="tips"></span></td>
                    <td>
                        <input list="data" class="form-control datas" name="datas" value="<%= pbf_list[i].fields.ylid %>" autocomplete="off">
                        <span class="tips"></span>
                        <datalist id="data">
                            <select class="form-control" name="ylid" id="ylid">
                            </select>
                        </datalist>
                    </td>
                    <td>
                        <input list="data_name" class="form-control data_name" name="data_name" value="<%= pbf_list[i].fields.ylname %>" autocomplete="off">
                        <span class="tips"></span>
                        <datalist id="data_name">
                            <select class="form-control" name="ylname" id="ylname">
                            </select>
                        </datalist>
                    </td>
                    <td><input type="text" name="bzgl" class="bzgl" value="<%= pbf_list[i].fields.bzgl %>"><span class="tips"></span></td>
                    <td><input type="text" name="topz" class="topz" value="<%= pbf_list[i].fields.topz %>"><span class="tips"></span></td>
                    <td><input type="text" name="lowz" class="lowz" value="<%= pbf_list[i].fields.lowz %>"><span class="tips"></span></td>
                    <td>
                        <select class="form-control dw" name="dw">
                            <% if (pbf_list[i].fields.dw == 'kg')
                                { %> <option value="kg">kg</option>
                                    <option value="g">g</option> <% }
                            else
                                { %> <option value="g">g</option>
                                    <option value="kg">kg</option> <% }
                            %>
                        </select>
                    </td>
                    <td><input type="number" name="jno" class="jno" value="<%= pbf_list[i].fields.jno %>" readonly><span class="tips"></span></td>
                    <td>
                        <% if (pbf_list[i].fields.lt)
                            { %> <input type="checkbox" name="lt" checked="checked" class="lt" value="1"> <% }
                        else
                            { %> <input type="checkbox" name="lt" class="lt" value="1"> <% }
                        %>
                        <input type="hidden" name="hlt" value="1" class="hlt">
                    </td>
                    <td>
                        <% if (pbf_list[i].fields.zs)
                            { %> <input type="checkbox" name="zs" checked="checked" class="zs" value="1"> <% }
                        else
                            { %> <input type="checkbox" name="zs" class="zs" value="1"> <% }
                        %>
                        <input type="hidden" name="hzs" value="1" class="hzs">
                    </td>
                    <td><a href="javascript:;" class="glyphicon glyphicon-remove f_delete"></a></td>
                </tr>
                <% } %>
            </tbody>
        </table>
        <input type="hidden" name="proof" value="<%- pbbh %>">
        <div class="form-actions well-sm clearfix">
            <a href="/admin/bc_formula/pb/{{ object_id }}/delete/" class="btn btn-danger deletelink col-xs-2 show-xs"><i class="fa fa-trash-o"></i></a>
            <div class="btn-group clearfix show-xs save-group col-xs-10">
                <button type="submit" class="default btn btn-primary col-xs-10" name="_save" data-loading-text="保存中.."><i class="fa fa-save"></i> 保存</button>
                <button type="button" class="more btn btn-primary col-xs-2" data-toggle="collapse" data-target=".nav-collapse.more-btns"><i class="fa fa-ellipsis-vertical"></i></button>
            </div>
            <button type="submit" class="default btn btn-primary hide-xs" name="_save"><i class="fa fa-save"></i> 保存</button>
            <div class="nav-collapse collapse more-btns">
                <input type="submit" class="btn btn-default" value="保存并增加另一个" name="_addanother"  />
                <input type="submit" class="btn btn-default" value="保存并继续编辑" name="_continue" />
            </div>
            <a href="/admin/bc_formula/pb/{{ object_id }}/delete/" class="btn btn-danger deletelink pull-right hide-xs"><i class="fa fa-trash-o"></i> 删除</a>
        </div>
    </script>
</div>
{% endblock %}