BarcodeSystem/urls.py
import xadmin
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('admin/', admin.site.urls),
    # 使用xadmin后台，不使用系统自带的admin
    path('admin/', xadmin.site.urls),
    path('product/', include('bc_product.urls', namespace='product')),
    path('production/', include('bc_production.urls', namespace='production')),
    path('rmaterial/', include('bc_rmaterial.urls', namespace='rmaterial')),
    path('formula/', include('bc_formula.urls', namespace='formula')),
]

bc_product/urls.py
from django.urls import path
from . import views


app_name = 'product'
urlpatterns = [
    path('save_product', views.save_product, name='save_product'),
    path('update_product', views.update_product, name='update_product'),
    path('query_product<int:num>', views.query_product, name='query_product'),
    path('quality_trace_back', views.quality_trace_back, name='quality_trace_back'),
]

bc_test/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path()
]

bc_product/models.py
from django.db import models
import os
import uuid


# 存储图片时，进行一次分类判断
def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    ext = filename.split('.')[-1]
    # filename = '{}.{}'.format(uuid.uuid4().hex[:8], ext)
    sub_folder = 'grf'
    if ext.lower() in ["jpg", "png", "gif"]:
        sub_folder = "picture"
    elif ext.lower() not in ["grf"]:
        sub_folder = "document"
    return os.path.join(str(instance.user.id), sub_folder, filename)


class Cpml(models.Model):
    cpid = models.CharField(primary_key=True, max_length=50, verbose_name='产品编号')
    cpmc = models.CharField(max_length=50, verbose_name='产品名称')
    gg = models.CharField(max_length=20, blank=True, null=True, verbose_name='规格')
    dbz = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True, verbose_name='单包重')
    pw = models.CharField(max_length=50, blank=True, null=True, verbose_name='批准文号')
    bz = models.CharField(max_length=50, blank=True, null=True, verbose_name='标准编号')
    cpxkz = models.CharField(max_length=50, blank=True, null=True, verbose_name='产品许可证')
    pbbh = models.OneToOneField('bc_formula.Pb', on_delete=models.CASCADE, verbose_name='配方编号')
    cpsx = models.FloatField(blank=True, null=True, verbose_name=' 包装上限')
    cpxx = models.FloatField(blank=True, null=True, verbose_name='包装下限')
    zbq = models.IntegerField(blank=True, null=True, verbose_name='保质期')  # 表单后面添加天字
    cctj = models.CharField(max_length=50, blank=True, null=True, verbose_name='储存条件')
    cpsb = models.CharField(max_length=50, blank=True, null=True, verbose_name='产品商标')
    cppic = models.ImageField(upload_to=user_directory_path, verbose_name='产品图片', null=True, blank=True)
    cpsm = models.FileField(upload_to=user_directory_path, verbose_name='产品说明', null=True, blank=True)
    tempname = models.FileField(upload_to=user_directory_path, verbose_name='成品标签模板', null=True, blank=True)  # (下完计划后，打印标签模板名称)
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.cpid

    class Meta:
        db_table = 'cpml'
        verbose_name = '产品'
        verbose_name_plural = '产品目录基础表'

bc_product/views.py
from django.shortcuts import render, redirect
from django.core import serializers
from django.http import JsonResponse, HttpResponse, Http404
from django.db import connection, transaction
from bc_production.models import Scjhb
from bc_formula.models import *
from .models import *
import re
import os

# C:\Users\44393\python\BarcodeSystem
BASE_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def query_product(request, num):
    if num == 1:
        pb_list = serializers.serialize('json', Pb.objects.filter(validity=False))
        return JsonResponse({'pb_list': pb_list})
    elif num == 2:
        cpid = request.GET.get('cpid')
        original_cpid = request.GET.get('Original_cpid')
        bool_product = 1
        # 若新值与原值相同，说明未作修改，bool_gys=1返回True，正确
        if not cpid == original_cpid:
            # 两值不同则对新值进行查询，返回True说明已有此数据，不能修改返回False，错误
            if Cpml.objects.filter(cpid=cpid).exists():
                bool_product = 0
        return JsonResponse({'bool_product': bool_product})
    elif num == 3:
        cpmc = request.GET.get('cpmc')
        original_cpmc = request.GET.get('Original_cpmc')
        bool_product = 1
        # 若新值与原值相同，说明未作修改，bool_gys=1返回True，正确
        if not cpmc == original_cpmc:
            # 两值不同则对新值进行查询，返回True说明已有此数据，不能修改返回False，错误
            if Cpml.objects.filter(cpmc=cpmc).exists():
                bool_product = 0
        return JsonResponse({'bool_product': bool_product})
    elif num == 4:
        pbbh = request.GET.get('pbbh')
        original_pbbh = request.GET.get('Original_pbbh')
        pb_bool = 0
        pbname = ''
        pb_list = Pb.objects.filter(pbbh=pbbh)
        if pb_list.exists():
            pbname = pb_list[0].pbname
            if not pbbh == original_pbbh:
                if pb_list[0].validity is True:
                    pb_bool = 2
                else:
                    pb_bool = 1
            else:
                pb_bool = 1
        return JsonResponse({'pb_bool': pb_bool, 'pbname': pbname})
    elif num == 5:
        pbname = request.GET.get('pbname')
        original_pbname = request.GET.get('Original_pbname')
        pb_bool = 0
        pbbh = ''
        pb_list = Pb.objects.filter(pbname=pbname)
        if pb_list.exists():
            pbbh = pb_list[0].pbbh
            if not pbname == original_pbname:
                if pb_list[0].validity is True:
                    pb_bool = 2
                else:
                    pb_bool = 1
            else:
                pb_bool = 1
        return JsonResponse({'pb_bool': pb_bool, 'pbbh': pbbh})
    # 点击删除按钮时，会到此进行逻辑处理，把相关的文件从服务器删除掉
    elif num == 6:
        cpid = request.GET.get('cpid')
        try:
            cpml = Cpml.objects.get(cpid=cpid)
            cppic = cpml.cppic
            cpsm = cpml.cpsm
            tempname = cpml.tempname
            with transaction.atomic():
                # 此变量为用户id/文档类型/文档名字--数据库存储的路径,需要把/转换为\
                user_type_cppic_str = str(cppic).replace('/', '\\')
                if user_type_cppic_str != '':
                    # 源文档的绝对路径
                    root_path = os.path.join(BASE_ROOT, 'static\media', user_type_cppic_str)
                    os.remove(root_path)
                user_type_cpsm_str = str(cpsm).replace('/', '\\')
                if user_type_cpsm_str != '':
                    # 源文档的绝对路径
                    root_path = os.path.join(BASE_ROOT, 'static\media', user_type_cpsm_str)
                    # 删除源文档
                    os.remove(root_path)
                user_type_tempname_str = str(tempname).replace('/', '\\')
                if user_type_tempname_str != '':
                    # 源文档的绝对路径
                    root_path = os.path.join(BASE_ROOT, 'static\media', user_type_tempname_str)
                    # 删除源文档
                    os.remove(root_path)
                pb = Pb.objects.get(pbbh=cpml.pbbh_id)
                pb.validity = False
                pb.save()
                cpml.delete()
        except Exception as e:
            print(e)
            raise Http404('异常')
        return redirect('/admin/bc_product/cpml/')


def update_product(request):
    product_id = request.GET.get('product_id')
    bool_product = 1
    # 查询产品表是否有此产品代码，出现异常则进入except环节
    try:
        cpml = Cpml.objects.get(cpid=product_id)
        cppic = str(cpml.cppic)
        cpsm = str(cpml.cpsm)
        tempname = str(cpml.tempname)
        pbname = cpml.pbbh.pbname
        dbz = cpml.dbz
        cpsx = cpml.cpsx
        cpxx = cpml.cpxx
        zbq = cpml.zbq
        if dbz is None:
            dbz = ''
        if cpsx is None:
            cpsx = ''
        if cpxx is None:
            cpxx = ''
        if zbq is None:
            zbq = ''
        return JsonResponse({'bool_product': bool_product, 'cpid': cpml.cpid, 'cpmc': cpml.cpmc, 'gg': cpml.gg,
                             'dbz': dbz, 'pw': cpml.pw, 'cpxkz': cpml.cpxkz, 'cpsx': cpsx, 'cpxx': cpxx,
                             'zbq': zbq, 'cctj': cpml.cctj, 'cpsb': cpml.cpsb, 'cppic': cppic, 'cpsm': cpsm,
                             'tempname': tempname, 'pbbh': cpml.pbbh_id, 'pbname': pbname, 'bz': cpml.bz})
    # 出现错误，讲错误返回到前端
    except Exception as e:
        print(e)
        return JsonResponse({'bool_product': 'error'})


def save_product(request):
    if request.method == 'POST':
        proof = request.POST.get('proof')
        cpid = request.POST.get('cpid')
        cpmc = request.POST.get('cpmc')
        gg = request.POST.get('gg')
        dbz = request.POST.get('dbz')
        pw = request.POST.get('pw')
        bz = request.POST.get('bz')
        pbbh = request.POST.get('data_cpml_pbbh')
        pbname = request.POST.get('data_cpml_pbname')
        cpsx = request.POST.get('cpsx')
        cpxx = request.POST.get('cpxx')
        zbq = request.POST.get('zbq')
        cctj = request.POST.get('cctj')
        cpsb = request.POST.get('cpsb')
        cpxkz = request.POST.get('cpxkz')
        cppic = request.FILES.get('cppic')
        cpsm = request.FILES.get('cpsm')
        tempname = request.FILES.get('tempname')
        addanother = request.POST.get('_addanother')
        add_edit = request.POST.get('_continue')
        user_id = request.user.id  # 此方法可获取当前登陆操作用户的ID，此次在这里使用的目的是保存文件时用来区分文件夹，文件夹的分类采用一个用户一个文件夹
        if cpid == '' or cpmc == '' or pbbh == '' or pbname == '':
            return redirect('/admin/bc_product/cpml/add/')
        if cppic is not None:
            if cppic.size > 5000000:
                return redirect('/admin/bc_product/cpml/add/')
        if cpsm is not None:
            if cpsm.size > 5000000:
                return redirect('/admin/bc_product/cpml/add/')
        if tempname is not None:
            if tempname.size > 5000000:
                return redirect('/admin/bc_product/cpml/add/')
        # 将浮点数值统一打包成一个元组进行统一判断
        judge_tuples = (dbz, cpsx, cpxx)
        # 调用业务逻辑处理类，获得一个实例
        logic_object = LogicProcessing()
        # 调用浮点数处理方法，将元组参数传递过去
        judge_result = logic_object.float_handle(judge_tuples)
        # 结果值为error，则重定向
        if judge_result == 'error':
            return redirect('/admin/bc_product/cpml/add/')
        # 为空全部转为None，因为数据表中得类型为整型与浮点型，存放空字符串是不行得
        if dbz == '':
            dbz = None
        if cpsx == '':
            cpsx = None
        if cpxx == '':
            cpxx = None
        if not zbq.isdigit():
            zbq = None
        # 连接数据库，得到一个游标，因为此视图不使用存储过程，所以此游标没有使用
        # cursor = connection.cursor()
        if not proof:
            try:
                if tempname is None:
                    return redirect('/admin/bc_product/cpml/add/')
                # 查看Pb表是否有此配方编号并且v值是F，不是F则说明此配方已经有产品使用，如果达不到这两种条件则重定向
                if not Pb.objects.filter(pbbh=pbbh, validity=False).exists():
                    return redirect('/admin/bc_product/cpml/add/')
                # 开启事务atomic上下文管理器，with块内的处理会纳入事务管理，有错误则全部回滚
                with transaction.atomic():
                    Cpml.objects.create(cpid=cpid, cpmc=cpmc, gg=gg, dbz=dbz, pw=pw, cpxkz=cpxkz, cpsx=cpsx, cpxx=cpxx,
                                        zbq=zbq, cctj=cctj, cpsb=cpsb, cppic=cppic, cpsm=cpsm, tempname=tempname,
                                        pbbh_id=pbbh, bz=bz, user_id=user_id)
                    # 新增成功后，将此配方编号的v值改为T，这样在新增产品时会自动排除此配方，因为一个配方只能有一个产品
                    pb_source_row = Pb.objects.get(pbbh=pbbh)
                    pb_source_row.validity = True
                    pb_source_row.save()
                if addanother is None and add_edit is None:
                    return redirect('/admin/bc_product/cpml/')
                elif addanother is not None and add_edit is None:
                    return redirect('/admin/bc_product/cpml/add/')
                elif addanother is None and add_edit is not None:
                    return redirect('/admin/bc_product/cpml/' + cpid + '/update/')
            except Exception as e:
                print(e)
                return redirect('/admin/bc_product/cpml/add/')
        else:
            try:
                # 获取修改之前的数据，将之前的文档删除掉，在添加新的文档
                cpml_source_row = Cpml.objects.get(cpid=proof)
                new_cppic = cpml_source_row.cppic
                new_cpsm = cpml_source_row.cpsm
                new_tempname = cpml_source_row.tempname
                # 开启事务atomic上下文管理器，with块内的处理会纳入事务管理，有错误则全部回滚
                with transaction.atomic():
                    # 判断是否为空，下方逻辑处理全部相同
                    if cppic is not None:
                        # 不为空去文件处理方法进行逻辑处理，返回的值可以直接放入数据库中
                        new_cppic = logic_object.file_handle(new_cppic, user_id, cppic)
                    if cpsm is not None:
                        new_cpsm = logic_object.file_handle(new_cpsm, user_id, cpsm)
                    if tempname is not None:
                        new_tempname = logic_object.file_handle(new_tempname, user_id, tempname)
                    pb_source_row = Pb.objects.get(pbbh=cpml_source_row.pbbh_id)

templates/bc_product/product_add.html
{% extends base_template %}
{% load i18n %}

{% load xadmin_tags %}
{% load crispy_forms_tags %}
{% block extrastyle %}
    <link rel="stylesheet" href="/static/bootstrap-3.3.7-dist/css/bootstrap.min.css">
    <script src="/static/js/jquery-1.12.4.min.js"></script>
    <script src="/static/bootstrap-3.3.7-dist/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="/static/lightbox2-master/dist/css/lightbox.css">
    <script src="/static/lightbox2-master/dist/js/lightbox.min.js"></script>
    <script src="/static/js/barcodesystem/bc_product/bc_product_add.js"></script>
    <link rel="stylesheet" href="/static/css/production.css">
{% endblock %}

{% block bodyclass %}{{ opts.app_label }}-{{ opts.object_name.lower }} change-form{% endblock %}

{% block nav_title %}{% if model_icon %}<i class="{{model_icon}}"><sub class="fa fa-{% if add%}plus{%else%}pencil{%endif%}"></sub></i> {% endif %}
{{ title }}{% endblock %}

{% block content %}
    <div class="container">
        <a href="/product/quality_trace_back?SPL=WORK000001">追溯</a>
        <form class="form-horizontal" method="post" action="{% url 'product:save_product' %}" enctype="multipart/form-data" id="form_submit">
            {%csrf_token%}
            <div class="form-group has-feedback">
                <label class="col-sm-2 control-label">产品编号<span class="" style="color: red">*</span></label>
                <div class="col-sm-4 form-box">
                    <input type="text" class="form-control" name="cpid" id="cpid" value="" aria-describedby="inputSuccess2Status">
                    <span class="tips"></span>
                </div>
                <label class="col-sm-2 control-label">产品名称<span class="" style="color: red">*</span></label>
                <div class="col-sm-4 form-box">
                    <input type="text" class="form-control" name="cpmc" id="cpmc" value="">
                    <span class="tips"></span>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">规格</label>
                <div class="col-sm-4 form-box">
                    <input type="text" class="form-control" name="gg" id="gg" value="">
                </div>
                <label class="col-sm-2 control-label">单包重</label>
                <div class="col-sm-4 form-box">
                    <input type="text" class="form-control" name="dbz" id="dbz" value="">
                    <span class="tips"></span>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">批准文号</label>
                <div class="col-sm-4 form-box">
                    <input type="text" class="form-control" name="pw" id="pw" value="">
                </div>
                <label class="col-sm-2 control-label">标准编号</label>
                <div class="col-sm-4 form-box">
                    <input type="text" class="form-control" name="bz" id="bz" value="">
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">配方编号<span class="" style="color: red">*</span></label>
                <div class="col-sm-4 form-box">
                    <input list="data_cpml_pbbh" class="form-control data_cpml_pbbh" name="data_cpml_pbbh" autocomplete="off">
                    <span class="tips"></span>
                    <datalist id="data_cpml_pbbh">
                        <select class="form-control" name="pbbh" id="pbbh">
                        </select>
                    </datalist>
                </div>
                <label class="col-sm-2 control-label">配方名称<span class="" style="color: red">*</span></label>
                <div class="col-sm-4 form-box">
                    <input list="data_cpml_pbname" class="form-control data_cpml_pbname" name="data_cpml_pbname" autocomplete="off">
                    <span class="tips"></span>
                    <datalist id="data_cpml_pbname">
                        <select class="form-control" name="pbname" id="pbname">
                        </select>
                    </datalist>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">包装上限</label>
                <div class="col-sm-4 form-box">
                    <input type="text" class="form-control" name="cpsx" id="cpsx" value="">
                    <span class="tips"></span>
                </div>
                <label class="col-sm-2 control-label">包装下限</label>
                <div class="col-sm-4 form-box">
                    <input type="text" class="form-control" name="cpxx" id="cpxx" value="">
                    <span class="tips"></span>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">保质期</label>
                <div class="col-sm-4 form-box">
                    <input type="number" class="form-control" name="zbq" id="zbq" value="">
                    <span class="tips"></span>
                </div>
                <label class="col-sm-2 control-label">储存条件</label>
                <div class="col-sm-4 form-box">
                    <input type="text" class="form-control" name="cctj" id="cctj" value="">
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">产品商标</label>
                <div class="col-sm-4 form-box">
                    <input type="text" class="form-control" name="cpsb" id="cpsb" value="">
                </div>
                <label class="col-sm-2 control-label">产品许可证</label>
                <div class="col-sm-4 form-box">
                    <input type="text" class="form-control" name="cpxkz" id="cpxkz" value="">
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">成品标签模板</label>
                <!-- 文件形式 <div class="col-sm-4 form-box">
                    <input type="file" class="form-control" name="tempname" value="" id="tempname">
                    <span class="tips"></span>
                </div>-->
                <div class="col-sm-4 form-box">
                    <input type="text" class="form-control" name="tempname" value="" id="tempname">
                    <span class="tips"></span>
                </div>
                <label class="col-sm-2 control-label">产品说明</label>
                <div class="col-sm-4 form-box">
                    <input type="file" class="form-control" name="cpsm" id="cpsm" value="">
                    <span class="tips"></span>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">产品图片</label>
                <div class="col-sm-4 form-box">
                    <input type="file" class="form-control" name="cppic" id="cppic">
                    <span class="tips"></span>
                </div>
            </div>
            <div class="form-actions well-sm clearfix">
                <div class="btn-group clearfix show-xs save-group col-xs-12">
                    <button type="submit" class="default btn btn-primary col-xs-10" name="_save" data-loading-text="保存中.."><i class="fa fa-save"></i> 保存</button>
                    <button type="button" class="more btn btn-primary col-xs-2" data-toggle="collapse" data-target=".nav-collapse.more-btns"><i class="fa fa-ellipsis-vertical"></i></button>
                </div>
                <button type="submit" class="default btn btn-primary hide-xs" name="_save"><i class="fa fa-save"></i> 保存</button>
                <div class="nav-collapse collapse more-btns">
                    <input type="submit" class="btn btn-default" value="保存并增加另一个" name="_addanother"  />
                    <input type="submit" class="btn btn-default" value="保存并继续编辑" name="_continue" />
                    <!--<input type="button" class="btn btn-default" id="btnPreview"  value="标签模板设计" />-->
                </div>
                <a href="/static/grf/模板.grf" class="btn btn-danger deletelink pull-right hide-xs">拷贝成品标签模板</a>
            </div>
    </form>
    </div>
{% endblock %}

templates/bc_product/quality_trace_back.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>
    <link rel="stylesheet" href="/static/bootstrap-3.3.7-dist/css/bootstrap.min.css">
    <script src="/static/js/jquery-1.12.4.min.js"></script>
    <script src="/static/bootstrap-3.3.7-dist/js/bootstrap.min.js"></script>
    <style>
        .title{
            font-size:16px;
            font-weight:bold;
            font-family:'微软雅黑';
        }
        .row{
            padding-top:5px;
        }
        .link{
            width: 100%;
            overflow: auto;
        }
    </style>
</head>
<body>
    <div class="container" style="background: red;">
        <div class="row">
            <div class="col-xs-11 col-xs-offset-1"><span class="title">产品名称：</span>{{ cpname }}</div>
            <div class="col-xs-11 col-xs-offset-1"><span class="title">生产日期：</span>{{ scrq }}</div>
            <div class="col-xs-11 col-xs-offset-1"><span class="title">计划单号：</span>{{ spl }}</div>
            <div class="col-xs-11 col-xs-offset-1"><img src="/static/media/{{ cppic }}" class="img-responsive img-rounded"></div>
            <div class="col-xs-11 col-xs-offset-1"><iframe src="/static/media/{{ cpsm }}" class="link"></iframe></div>
        </div>
        <br>
    </div>
</body>
</html>